# -*- coding: utf-8 -*-
"""IntroduçãoRedesNeuraisPyTorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MLC6pLXUFkC0I3WNiceZZr50L8z0K7yb

# **Tensores**

##Tipos de tensores
"""

import torch

lista = [[1,2,3],
         [4,5,6]]
tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

"""##A partir de arrays Numpy"""

import numpy as np
arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

print(arr)
print(tns)

"""##Tensores inicializados"""

tns1 = torch.ones(2, 3)
tns0 = torch.zeros(3, 5)
tnsr = torch.randn(3, 3)

print(tns1)
print(tns0)
print(tnsr)

"""##Tensor para array numpy"""

print(type(tnsr))
arr = tnsr.data.numpy()
print(arr)
print(type(arr))

"""##Indexação"""

print(tnsr)
tnsr[0,2] = -10
print('')
print(tnsr)

print('')
print(tnsr[:,2])

"""##Operações com tensores"""

tns = tnsr[0:2, :]
print(tns)
print(tns1)

#soma
print('')
print('soma')
print(tns+tns1)

#multiplicação de matrizes
print('')
print('multiplicação de matrizes')
print(torch.mm(tns, tns1.T))

#multiplicação elemento a elemento
print('')
print('multiplicação elemente a elemento')
print(tns*tns1)

"""##Função .size() e .view()"""

tns = torch.randn(2,2,3)
print(tns)

print(tns.size())


tns = tns.view(12)
print(tns)

"""##GPU Cast"""

import torch

tns = torch.randn(10)
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)

tns = tns.to(device)
print(tns)

"""# **Percetron**

##Classificação Linear
"""

import numpy as np
import matplotlib.pyplot as plt

a = -1
b = 4
c = 0.4

#ax + by + c = 0
#y = (-a*x -c)/b

def plotline(a, b, c):
  x = np.linspace(-2, 4, 50)
  y = (-a*x -c)/b

  plt.axvline(0, -1, 1, color='k', linewidth=1)
  plt.axhline(0, -2, 4, color='k', linewidth=1)
  plt.plot(x,y)
  plt.grid(True)

plotline(a, b, c)

p1 = (2, 0.4)
p2 = (1, 0.6)
p3 = (3, -0.4)

plotline(a,b,c)
plt.plot(p1[0], p1[1], color='b', marker='o')
plt.plot(p2[0], p2[1], color='g', marker='o')
plt.plot(p3[0], p3[1], color='r', marker='o')

ret1 = a*p1[0] + b*p1[1] + c
print("ponto 1: " "%.2f" %ret1)

ret2 = a*p2[0] + b*p2[1] + c
print("ponto 2: " "%.2f" %ret2)

ret3 = a*p3[0] + b*p3[1] + c
print("ponto 3: " "%.2f" %ret3)

"""###Exercício"""

from sklearn.datasets import make_classification
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(20)

X, Y = make_classification(n_features=2, n_redundant=0, n_informative=2, n_clusters_per_class=1)

plt.scatter(X[:, 0], X[:, 1], marker='o', c=Y, edgecolor='k')
p = X[10]
print(Y[10])
plt.plot(p[0], p[1], marker='^', markersize=20)

def plotmodel(w1, w2, b):
  plt.scatter(X[:, 0], X[:, 1], marker='o', c=Y, edgecolor='k')

  xmin, xmax = plt.gca().get_xlim()
  ymin, ymax = plt.gca().get_ylim()

  x = np.linspace(-2, 4, 50)
  y = (-w1*x -b)/w2

  plt.axvline(0, -1, 1, color='k', linewidth=1)
  plt.axhline(0, -2, 4, color='k', linewidth=1)
  plt.plot(x,y)
  plt.grid(True)

  plt.xlim(xmin, xmax)
  plt.ylim(ymin, ymax)

w1 = 0.6
w2 = -1
b = 0.5
plotmodel(w1, w2, b)

p = (-1, 1)
print(w1 * p[0] + w2 * p[1] + b)

def classify(ponto, w1, w2, b):
  ret = w1 * ponto[0] + w2 * ponto[1] + b
  if ret >= 0:
    return 0, 'blue'
  else:
    return 1, 'yellow'

p = (-1, -1)
classe, cor = classify(p, w1, w2, b)
print(classe, cor)

plotmodel(w1, w2, b)
plt.plot(p[0], p[1], marker='^', markersize=20, color=cor)

acertos = 0
for k in range(len(X)):
  categ, _ = classify(X[k], w1, w2, b)
  if categ == Y[k]:
    acertos += 1

print("Acurácia: {0}".format(100*acertos/len(X)))

"""##Camada Linear"""

import torch
from torch import nn #neural network

torch.manual_seed(42)

perceptron = nn.Linear(in_features=3, out_features=1)
print(perceptron)

for nome, tensor in perceptron.named_parameters():
  print(nome, tensor.data)


  print('')
  print(perceptron.weight.data)
  print('')
  print(perceptron.bias.data)

w1, w2, w3 = perceptron.weight.data.numpy()[0]
b = perceptron.bias.data.numpy()
print(w1, w2, w3, b)

#w1 * x1 + w2 * x2 + w3 * x3 + b = 0

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def plot3d(perceptron):

  w1, w2, w3 = perceptron.weight.data.numpy()[0]
  b = perceptron.bias.data.numpy()

  X1 = np.linspace(-1,1,10)
  X2 = np.linspace(-1,1,10)

  X1, X2 = np.meshgrid(X1,X2)

  X3 = (b - w1*X1 - w2*X2) / w3

  fig = plt.figure(figsize=(10, 8))

  ax = fig.add_subplot(111, projection='3d')
  ax.view_init(azim=180)

  ax.plot_surface(X1, X2, X3, cmap='plasma')

plot3d(perceptron)

X = torch.Tensor([0, 1, 2])
y = perceptron(X)

print(y)

plot3d(perceptron)
plt.plot([X[0]], [X[1]], [X[2]], color='r', marker='^', markersize=20)

"""# **Funções de Ativação**"""

import torch
from torch import nn

from sklearn.datasets import make_classification
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(43)

X, Y = make_classification(n_features=2, n_redundant=0, n_informative=2, n_clusters_per_class=1)
def plotmodel(w1, w2, b):
  plt.scatter(X[:, 0], X[:, 1], marker='o', c=Y, edgecolor='k')

  xmin, xmax = plt.gca().get_xlim()
  ymin, ymax = plt.gca().get_ylim()

  x = np.linspace(-2, 4, 50)
  y = (-w1*x -b)/w2

  plt.axvline(0, -1, 1, color='k', linewidth=1)
  plt.axhline(0, -2, 4, color='k', linewidth=1)
  plt.plot(x,y)
  plt.grid(True)

  plt.xlim(xmin, xmax)
  plt.ylim(ymin, ymax)

w1 = 0.6
w2 = -1
b = 0.5
plotmodel(w1, w2, b)

p = (-1, 1)

perceptron = nn.Linear(2, 1)
sigmoide = nn.Sigmoid()

print(perceptron.weight.data)
print(perceptron.bias.data)

perceptron.weight = nn.Parameter(torch.Tensor([[0.6, -1]]))
perceptron.bias = nn.Parameter(torch.Tensor([0.5]))

w1 = 0.6
w2 = -1
b = 0.5

markers = ['^', 'v', '>', '<']
colors = ['r', 'g', 'b', 'gray']

plt.figure(figsize=(8, 6))
plotmodel(w1, w2, b)
for k, idx in enumerate ([17, 21, 43, 66]):
  x = torch.Tensor(X[idx])

  ret = perceptron(x)
  ret = sigmoide(ret)

  act_limiar = 0 if ret.data < 0 else 1

  label = 'ret: {:5.2f}'.format(ret.data.numpy()[0]) + ' limiar: {:4.2f}'.format(act_limiar) + ' act: {:5.2f}'.format(ret.data.numpy()[0])
  plt.plot(x[0], x[1], marker=markers[k], color=colors[k], markersize=10, label=label)

plt.legend()
plt.show()

"""# **Redes Neurais**

##Arquitetura no Pytorch
"""

from sklearn.datasets import make_moons
import matplotlib.pyplot as plt

X1, Y1 = make_moons(n_samples=300, noise=0.2)

plt.scatter(X1[:, 0], X1[:, 1], marker='o', c=Y1, edgecolor='k')

"""##nn.Sequential"""

import torch
from torch import nn

input_size = 2
hidden_size = 8
output_size = 1

net = nn.Sequential(nn.Linear(in_features=input_size, out_features=hidden_size), #hidden (escondida)
                    nn.ReLU(), #ativação não linear
                    nn.Linear(in_features=hidden_size, out_features=output_size)) #output (saída)
print(net)

from torchsummary import summary
summary(net, input_size=(1, input_size))

"""##Forward"""

print(X1.shape)
tensor = torch.from_numpy(X1).float()
pred = net(tensor)
print(pred.size)

"""## Class nn/Module"""

import torch
from torch import nn
class MinhaRede(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super(MinhaRede, self).__init__()

    #Definir a arquitetura
    self.hidden = nn.Linear(input_size, hidden_size)
    self.relu = nn.ReLU()
    self.output = nn.Linear(hidden_size, output_size)

  def forward(self, x):

    #Gerar uma saída a partir do X
    hidden = self.relu(self.hidden(x))
    output = self.output(hidden)

    return output

input_size = 2
hidden_size = 8
output_size = 1
net = MinhaRede(input_size, hidden_size, output_size) ## O método __init__()
print(net)

print(X1.shape)
tensor = torch.from_numpy(X1).float()
pred = net(tensor)
print(pred.size())

"""##Subindo informações na GPU"""

if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

print(device)

input_size = 2
hidden_size = 8
output_size = 1
net = MinhaRede(input_size, hidden_size, output_size) ## O método __init__()
net = net.to(device)
print(net)

print(X1.shape)
tensor = torch.from_numpy(X1).float()
tensor = tensor.to(device)
ptrf = net(tensor)
print(ptrf.size())