# -*- coding: utf-8 -*-
"""TreinandoRedeNeuralPytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1DXPI8680nYQUsEYxYdPNxg4YnAtw3T

# **Funções de Perda**
"""

import torch
from torch import nn

if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)

from sklearn import datasets
wine = datasets.load_wine()
data = wine.data
target = wine.target

print(data.shape, target.shape)
print(wine.feature_names, wine.target_names)

class WineClassifier(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super(WineClassifier, self).__init__()

    self.hidden = nn.Linear(input_size, hidden_size)
    self.output = nn.Linear(hidden_size, output_size)
    self.relu = nn.ReLU()
    self.softmax = nn.Softmax(dim=1)

  def forward(self, x):
    feature = self.relu(self.hidden(x))
    output = self.softmax(self.output(feature))
    return output

input_size = data.shape[1]
hidden_size = 32
output_size = len(wine.target_names)

net = WineClassifier(input_size, hidden_size, output_size).to(device) #cast na GPU
print(net)

"""##Classificação"""

criterion = nn.CrossEntropyLoss().to(device) #cast na GPU

Xtns = torch.from_numpy(data).float()
Ytns = torch.from_numpy(target)

#cast na GPU
Xtns = Xtns.to(device)
Ytns = Ytns.to(device)

print(Xtns.dtype, Ytns.dtype)

pred = net(Xtns)

print(pred.shape, Ytns.shape)

print(pred[0].data, Ytns[0].data)

loss = criterion(pred, Ytns)
print(loss)

"""##Regressão"""

from sklearn import datasets

diabetes  = datasets.load_diabetes()
data = diabetes.data
target = diabetes.target

print(data.shape, target.shape)
print(data[14])
print(target[14])

class WineClassifier(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super(WineClassifier, self).__init__()

    self.hidden = nn.Linear(input_size, hidden_size)
    self.output = nn.Linear(hidden_size, output_size)
    self.relu = nn.ReLU()
    self.softmax = nn.Softmax(dim=1)

  def forward(self, x):
    feature = self.relu(self.hidden(x))
    output = self.softmax(self.output(feature))
    return output

input_size = data.shape[1]
hidden_size = 32
output_size = 1 #Regressão da Progressão da diabetes, por isso é só uma variável

net = WineClassifier(input_size, hidden_size, output_size).to(device) #cast na GPU
print(net)

criterion = nn.MSELoss().to(device)

#Cast na GPU
Xtns = torch.from_numpy(data).float().to(device)
Ytns = torch.from_numpy(target).float().to(device)

print(Xtns.shape, Ytns.shape)

pred = net(Xtns)

loss = criterion(pred, Ytns)
print(loss.data)

"""# **Otimizando uma rede em PyTorch**"""

import matplotlib.pyplot as plt
from sklearn import datasets

features = [0, 9]

wine = datasets.load_wine()
data = wine.data[:, features]
target = wine.target

plt.scatter(data[:, 0], data[:, 1], c=target, s=15, cmap=plt.cm.brg)
plt.xlabel(wine.feature_names[features[0]])
plt.ylabel(wine.feature_names[features[1]])

"""##Normalização"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data = scaler.fit_transform(data)

"""##Instanciando sua rede"""

import torch
from torch import nn

if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)

input_size = data.shape[1]
hidden_size = 32
output_size = len(wine.target_names) #número de classes

net = nn.Sequential(
    nn.Linear(input_size, hidden_size),
    nn.ReLU(),
    nn.Linear(hidden_size, output_size),
    nn.Softmax()
)

net = net.to(device)

"""##Visualizando a fronteira de decisão"""

import numpy as np

def plot_boundary(X, y, model):
  x_min, x_max = X[:, 0].min()-0.1, X[:, 0].max()+0.1
  y_min, y_max = X[:, 1].min()-0.1, X[:, 1].max()+0.1

  spacing = min(x_max - x_min, y_max - y_min) / 100

  XX, YY = np.meshgrid(np.arange(x_min, x_max, spacing),
                       np.arange(y_min, y_max, spacing))

  data = np.hstack((XX.ravel().reshape(-1,1),
                    YY.ravel().reshape(-1,1)))

  # For binary problems
  # db_prob = model(Variable(torch.Tensor(data)).cuda() )
  # clf = np.where(db_prob.cpu().data < 0.5,0,1)

  # For multi-class problems
  db_prob = model(torch.Tensor(data).to(device) )
  clf = np.argmax(db_prob.cpu().data.numpy(), axis=-1)

  Z = clf.reshape(XX.shape)

  plt.contourf(XX, YY, Z, cmap=plt.cm.brg, alpha=0.5)
  plt.scatter(X[:,0], X[:,1], c=y, edgecolors='k', s=25, cmap=plt.cm.brg)

plot_boundary(data, target, net)

from torch import optim

#Função de Perda
criterion = nn.CrossEntropyLoss().to(device)

#Otimizador: Descida do Gradiente
#Stochastic Gradient Descent
optimizer = optim.SGD(net.parameters(), lr=1e-3)

X = torch.FloatTensor(data).to(device) #GPU
Y = torch.LongTensor(target).to(device)

"""##Treinando um modelo"""

for i in range(100):
  #Forward
  pred= net(X)
  loss = criterion(pred, Y)

  #Backpropagation
  loss.backward()
  optimizer.step()
  if i % 10 == 0:
    plt.figure()
    plot_boundary(data, target, net)

"""#**DataLoader e Fluxo de Treinamento**"""

import torch
from torch import nn, optim
import numpy as np
import matplotlib.pyplot as plt
#Torchvision datasets
from torchvision import datasets
#Torchvision transforms
from torchvision import transforms
#DataLoader
from torch.utils.data import DataLoader

args =  {
    'batch_size': 20,
    'num_workers': 4,
    'lr': 1e-4,
    'weight_decay': 5e-4,
    'num_classes;': 10,
    'num_epochs': 30
}

if torch.cuda.is_available():
  args['device'] = torch.device('cuda')
else:
  args['device'] = torch.device('cpu')
print(args['device'])

"""##Datasets"""

train_set = datasets.MNIST(root='./', train=True, download=True, transform=transforms.ToTensor())
test_set = datasets.MNIST(root='./', train=False, download=False, transform=transforms.ToTensor())

print('Amostra de treinos: ' + str(len(train_set)) + '\nAmostra de teste: ' + str(len(test_set)))

print(type(train_set))
print(type(train_set[0]))

for i in range(3):
  dado, rotulo = train_set[i]

  plt.figure()
  plt.imshow(dado[0])
  plt.title('Rotulo: ' + str(rotulo))

"""##DataLoader"""

train_loader = DataLoader(train_set,
                          batch_size=args['batch_size'],
                          shuffle=True,
                          num_workers=args['num_workers'])

test_loader = DataLoader(test_set,
                         batch_size=args['batch_size'],
                         shuffle=True,
                         num_workers=args['num_workers'])

for batch in train_loader:
  dado, rotulo = batch
  print(dado.size(), rotulo.size())

  plt.imshow(dado[0][0])
  plt.title('Rotulo: ' + str(rotulo[0]))
  break

class MLP(nn.Module):

  def __init__(self, input_size, hidden_size, out_size):
    super(MLP, self).__init__()

    self.features  = nn.Sequential(
                      nn.Linear(input_size, hidden_size),
                      nn.ReLU(),
                      nn.Linear(hidden_size, hidden_size),
                      nn.ReLU()
                    )
    self.out     = nn.Linear(hidden_size, out_size)
    self.softmax = nn.Softmax()

  def forward(self, X):

    X = X.view(X.size(0), -1)

    feature = self.features(X)
    output  = self.softmax(self.out(feature))

    return output

input_size  = 28 * 28
hidden_size = 128
out_size    = 10 #classes

torch.manual_seed(42)
net = MLP(input_size, hidden_size, out_size).to(args['device']) #cast na GPU

criterion = nn.CrossEntropyLoss().to(args['device'])
optimizer = optim.Adam(net.parameters(), lr=args['lr'], weight_decay=args['weight_decay'])

"""##Fluxo de treinamento"""

for epoch in range(args['num_epochs']):

  epoch_loss = []
  for batch in train_loader:

    dado, rotulo = batch

    # Cast na GPU
    dado   = dado.to(args['device'])
    rotulo = rotulo.to(args['device'])

    # Forward
    pred = net(dado)
    loss = criterion(pred, rotulo)
    epoch_loss.append(loss.cpu().data)

    # Backward
    loss.backward()
    optimizer.step()

  epoch_loss = np.asarray(epoch_loss)

  print("Epoca %d, Loss: %.4f +\- %.4f" % (epoch, epoch_loss.mean(), epoch_loss.std()) )

"""#**Datasets e Fluxo de Validação**"""

import torch
from torch import nn, optim

from torch.utils.data import DataLoader
from torch.utils.data import Dataset

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

args =  {
    'batch_size': 20,
    'num_workers': 4,
    'lr': 1e-4,
    'weight_decay': 5e-4,
    'num_classes;': 10,
    'num_epochs': 30
}

if torch.cuda.is_available():
  args['device'] = torch.device('cuda')
else:
  args['device'] = torch.device('cpu')
print(args['device'])

#baixando datasets
! wget /content/bike+sharing+dataset.zip
! unzip /content/bike+sharing+dataset.zip

! ls

#Visualizando os dados
df = pd.read_csv('/content/hour.csv')
print(len(df))
df.head()

#Tratamento de dados
torch.manual_seed(1)
indices = torch.randperm(len(df)).tolist()

train_size = int(0.8*len(df))
df_train = df.iloc[indices[:train_size]]
df_test = df.iloc[indices[train_size:]]

print(len(df_train), len(df_test))
display(df_test.head())
df_train.to_csv('bike_train.csv', index=False)
df_test.to_csv('bike_test.csv', index=False)

!ls

"""##Classe Dataset"""

class Bicreta(Dataset):
  def __init__(self, csv_path):
    self.dados = pd.read_csv(csv_path).to_numpy()

  def __getitem__(self, idx):
    sample = self.dados[idx][2:14]
    label = self.dados[idx][-1:]

    #coverte pra tensor
    sample = torch.from_numpy(sample.astype(np.float32))
    label = torch.from_numpy(label.astype(np.float32))

    return sample, label

  def __len__(self):
    return len(self.dados)

train_set = Bicreta('bike_train.csv')
test_set = Bicreta('bike_test.csv')

dado, rotulo = train_set[0]
print(rotulo)
print(dado)

"""##Dataloader"""

train_loader = DataLoader(train_set,
                          batch_size=args['batch_size'],
                          shuffle=True,
                          num_workers=args['num_workers'])

test_loader = DataLoader(test_set,
                         batch_size=args['batch_size'],
                         shuffle=True,
                         num_workers=args['num_workers'])

for batch in train_loader:
  dado, rotulo = batch
  print(dado.size(), rotulo.size())

  break

#Implementando o mesmo MLP mas muda a saída
class MLP(nn.Module):

  def __init__(self, input_size, hidden_size, out_size):
    super(MLP, self).__init__()

    self.features  = nn.Sequential(
                      nn.Linear(input_size, hidden_size),
                      nn.ReLU(),
                      nn.Linear(hidden_size, hidden_size),
                      nn.ReLU()
                    )
    self.out     = nn.Linear(hidden_size, out_size)

  def forward(self, X):

    feature = self.features(X)
    output  = self.out(feature)

    return output

input_size  = len(train_set[0][0])
hidden_size = 128
out_size    = 10 #variáveis que serão preditas

net = MLP(input_size, hidden_size, out_size).to(args['device']) #cast na GPU

criterion = nn.L1Loss().to(args['device'])
optimizer = optim.Adam(net.parameters(), lr=args['lr'], weight_decay=args['weight_decay'])

def train(train_loader, net, epoch):
  epoch_loss = []
  for epoch in range(args['num_epochs']):

    epoch_loss = []
    for batch in train_loader:

      dado, rotulo = batch

      # Cast na GPU
      dado   = dado.to(args['device'])
      rotulo = rotulo.to(args['device'])

      # Forward
      pred = net(dado)
      loss = criterion(pred, rotulo)
      epoch_loss.append(loss.cpu().data)

      # Backward
      loss.backward()
      optimizer.step()

    epoch_loss = np.asarray(epoch_loss)

    print("Epoca %d, Loss: %.4f +\- %.4f" % (epoch, epoch_loss.mean(), epoch_loss.std()) )

def train(train_loader, net, epoch):
  net.train()
  epoch_loss = []
  for epoch in range(args['num_epochs']):

    epoch_loss = []
    for batch in train_loader:

      dado, rotulo = batch

      # Cast na GPU
      dado   = dado.to(args['device'])
      rotulo = rotulo.to(args['device'])

      # Forward
      pred = net(dado)
      loss = criterion(pred, rotulo)
      epoch_loss.append(loss.cpu().data)

      # Backward
      loss.backward()
      optimizer.step()

    epoch_loss = np.asarray(epoch_loss)

    print("Epoca %d, Loss: %.4f +\- %.4f" % (epoch, epoch_loss.mean(), epoch_loss.std()) )

def test(test_loader, net, epoch):

  net.eval()
  with torch.no_grad():
    epoch_loss = []
    for epoch in range(args['num_epochs']):

      epoch_loss = []
      for batch in train_loader:

        dado, rotulo = batch

        # Cast na GPU
        dado   = dado.to(args['device'])
        rotulo = rotulo.to(args['device'])

        # Forward
        pred = net(dado)
        loss = criterion(pred, rotulo)
        epoch_loss.append(loss.cpu().data)

      epoch_loss = np.asarray(epoch_loss)

      print("Epoca %d, Loss: %.4f +\- %.4f" % (epoch, epoch_loss.mean(), epoch_loss.std()) )

for epoch in range(args['num_epochs']):
  train(train_loader, net, epoch)
  test(test_loader, net, epoch)